/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("players").del();
  await knex("players").insert([
    {
      id: 1,
      player_name: "Jordan Romano",
      jersey_number: 68,
      gender: "male",
      bats: "right",
      throws: "right",
      team_id: 1,
    },
    {
      id: 2,
      player_name: "Vladimir Guerrero Jr.",
      jersey_number: 27,
      gender: "male",
      bats: "right",
      throws: "right",
      team_id: 1,
    },
    {
      id: 3,
      player_name: "Ernie Clement",
      jersey_number: 28,
      gender: "male",
      bats: "right",
      throws: "right",
      team_id: 1,
    },
    {
      id: 4,
      player_name: "Alejandro Kirk",
      jersey_number: 30,
      gender: "male",
      bats: "right",
      throws: "right",
      team_id: 1,
    },
    {
      id: 5,
      player_name: "Davis Schneider",
      jersey_number: 36,
      gender: "male",
      bats: "right",
      throws: "right",
      team_id: 1,
    },
    {
      id: 6,
      player_name: "George Springer",
      jersey_number: 4,
      gender: "male",
      bats: "right",
      throws: "right",
      team_id: 1,
    },
    {
      id: 7,
      player_name: "Daulton Varsho",
      jersey_number: 25,
      gender: "male",
      bats: "left",
      throws: "right",
      team_id: 1,
    },
    {
      id: 8,
      player_name: "Addison Barger",
      jersey_number: 47,
      gender: "male",
      bats: "left",
      throws: "right",
      team_id: 1,
    },
    {
      id: 9,
      player_name: "Bo Bichette",
      jersey_number: 11,
      gender: "male",
      bats: "right",
      throws: "right",
      team_id: 1,
    },
    {
      id: 10,
      player_name: "Kevin Gausman",
      jersey_number: 34,
      gender: "male",
      bats: "left",
      throws: "right",
      team_id: 1,
    },
    {
      id: 11,
      player_name: "Ian Happ",
      jersey_number: 8,
      gender: "male",
      bats: "left",
      throws: "right",
      team_id: 2,
    },
    {
      id: 12,
      player_name: "Dansby Swanson",
      jersey_number: 7,
      gender: "male",
      bats: "right",
      throws: "right",
      team_id: 2,
    },
    {
      id: 13,
      player_name: "Seiya Suzuki",
      jersey_number: 27,
      gender: "male",
      bats: "right",
      throws: "right",
      team_id: 2,
    },
    {
      id: 14,
      player_name: "Cody Bellinger",
      jersey_number: 24,
      gender: "male",
      bats: "left",
      throws: "left",
      team_id: 2,
    },
    {
      id: 15,
      player_name: "Isaac Paredes",
      jersey_number: 17,
      gender: "male",
      bats: "right",
      throws: "right",
      team_id: 2,
    },
    {
      id: 16,
      player_name: "Patrick Wisdom",
      jersey_number: 16,
      gender: "male",
      bats: "right",
      throws: "right",
      team_id: 2,
    },
    {
      id: 17,
      player_name: "Nico Hoerner",
      jersey_number: 2,
      gender: "male",
      bats: "right",
      throws: "right",
      team_id: 2,
    },
    {
      id: 18,
      player_name: "Pete Crow-Armstrong",
      jersey_number: 52,
      gender: "male",
      bats: "left",
      throws: "left",
      team_id: 2,
    },
    {
      id: 19,
      player_name: "Miguel Amaya",
      jersey_number: 9,
      gender: "male",
      bats: "right",
      throws: "right",
      team_id: 2,
    },
    {
      id: 20,
      player_name: "Javier Assad",
      jersey_number: 72,
      gender: "male",
      bats: "right",
      throws: "right",
      team_id: 2,
    },
    {
      id: 21,
      player_name: "Corbin Burnes",
      jersey_number: 39,
      gender: "male",
      bats: "right",
      throws: "right",
      team_id: 3,
    },
    {
      id: 22,
      player_name: "Gunnar Henderson",
      jersey_number: 2,
      gender: "male",
      bats: "left",
      throws: "right",
      team_id: 3,
    },
    {
      id: 23,
      player_name: "Adley Rutschman",
      jersey_number: 35,
      gender: "male",
      bats: "switch",
      throws: "right",
      team_id: 3,
    },
    {
      id: 24,
      player_name: "Ryan O'Hearn",
      jersey_number: 32,
      gender: "male",
      bats: "left",
      throws: "left",
      team_id: 3,
    },
    {
      id: 25,
      player_name: "Anthony Santander",
      jersey_number: 25,
      gender: "male",
      bats: "switch",
      throws: "right",
      team_id: 3,
    },
    {
      id: 26,
      player_name: "Colton Cowser",
      jersey_number: 17,
      gender: "male",
      bats: "left",
      throws: "right",
      team_id: 3,
    },
    {
      id: 27,
      player_name: "Eloy Jiménez",
      jersey_number: 72,
      gender: "male",
      bats: "right",
      throws: "right",
      team_id: 3,
    },
    {
      id: 28,
      player_name: "Cedric Mullins",
      jersey_number: 31,
      gender: "male",
      bats: "left",
      throws: "left",
      team_id: 3,
    },
    {
      id: 29,
      player_name: "Ramón Urías",
      jersey_number: 29,
      gender: "male",
      bats: "right",
      throws: "right",
      team_id: 3,
    },
    {
      id: 30,
      player_name: "Jackson Holliday",
      jersey_number: 7,
      gender: "male",
      bats: "left",
      throws: "right",
      team_id: 3,
    },
    {
      id: 31,
      player_name: "Gleyber Torres",
      jersey_number: 25,
      gender: "male",
      bats: "right",
      throws: "right",
      team_id: 4,
    },
    {
      id: 32,
      player_name: "Juan Soto",
      jersey_number: 22,
      gender: "male",
      bats: "left",
      throws: "left",
      team_id: 4,
    },
    {
      id: 33,
      player_name: "Aaron Judge",
      jersey_number: 99,
      gender: "male",
      bats: "right",
      throws: "right",
      team_id: 4,
    },
    {
      id: 34,
      player_name: "Austin Wells",
      jersey_number: 28,
      gender: "male",
      bats: "left",
      throws: "right",
      team_id: 4,
    },
    {
      id: 35,
      player_name: "Giancarlo Stanton",
      jersey_number: 27,
      gender: "male",
      bats: "right",
      throws: "right",
      team_id: 4,
    },
    {
      id: 36,
      player_name: "Jazz Chisholm Jr.",
      jersey_number: 13,
      gender: "male",
      bats: "left",
      throws: "right",
      team_id: 4,
    },
    {
      id: 37,
      player_name: "Anthony Rizzo",
      jersey_number: 48,
      gender: "male",
      bats: "left",
      throws: "left",
      team_id: 4,
    },
    {
      id: 38,
      player_name: "Anthony Volpe",
      jersey_number: 11,
      gender: "male",
      bats: "right",
      throws: "right",
      team_id: 4,
    },
    {
      id: 39,
      player_name: "Alex Verdugo",
      jersey_number: 24,
      gender: "male",
      bats: "left",
      throws: "left",
      team_id: 4,
    },
    {
      id: 40,
      player_name: "Nestor Cortes",
      jersey_number: 65,
      gender: "male",
      bats: "right",
      throws: "left",
      team_id: 4,
    },
  ]);
};
